version: '3.1'

services: 
    db:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      volumes:
        -  ./data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: 123456
        POSTGRES_USER: developia
        POSTGRES_DB: postgres807

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080